#
# Makefile for the Linux NFC device drivers.
#

obj-$(CONFIG_NXP_NFC_I2C)	+= pn7160/
obj-$(CONFIG_NXP_NFC_SPI)	+= pn7160/
obj-$(CONFIG_NXP_NFC_PN7220_I2CS) += pn7220_i2cs/
obj-$(CONFIG_NXP_NFC_PN7220_I2CMS) += pn7220_i2cms/